version: '3.8'

services:
  backend:
    build: ./backend
    container_name: genai-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - generated_images:/app/app/static/images
      - model_cache:/app/model_cache
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          memory: 4G
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: genai-frontend
    ports:
      - "80:80"
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=8000
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  generated_images:
    driver: local
  model_cache:
    driver: local